[build]
builder = "nixpacks"
buildCommand = "uv sync"
[deploy]
startCommand = "uvicorn src.backend.main:app  --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/health"
healthcheckTimeout = 100
startTimeout = 100